### ISSUE TITLE
Global-Mixin ?

### ISSUE THREAD

**Issue by Sarapulov** [fabioguarrasi/Zendesk-Apps-Boilerplate-Vuejs---Requirejs-ES5#6]
https://github.com/fabioguarrasi/require_vue_app/blob/5adf2db739fa72a7492b45bb3cca4e402efa882c/assets/src/main.js#L34

can't you do it in Vue way? Global Mixin? https://vuejs.org/v2/guide/mixins.html#Global-Mixin

It may only make it available for VueJS components though.
So client.js may not benefit from.
Just a thought.

**Comment by fabioguarrasi** [comment]
@Sarapulov what about something like this? https://stackoverflow.com/questions/37694243/using-lodash-in-all-of-vue-component-template

**Comment by Sarapulov** [comment]
Thats cool

**Comment by fabioguarrasi** [comment]
@Sarapulov what about for classes where we don't import Vue? like `ZAFClient`? how can we use underscore there?

**Comment by Sarapulov** [comment]
That is what i am saying as well `It may only make it available for VueJS components though.`
If this is a problem - let's keep things as they are
