### ISSUE TITLE
Width

### ISSUE THREAD

**Issue by erlipknot** [fabioguarrasi/Zendesk-Apps-Boilerplate-Vuejs---Requirejs-ES5#7]
Could you please modify the width?

You have 700px when it should be 100%.

https://github.com/fabioguarrasi/require_vue_app/blob/5adf2db739fa72a7492b45bb3cca4e402efa882c/assets/src/libs/ZAFClient.js#L22

Thanks!!

**Comment by fabioguarrasi** [comment]
done
